#ifndef _GLOBALCONFIG_H_
#define _GLOBALCONFIG_H_

#define USE_HARDCORD_TABLE
//#define _USE_Q7_8_FIXEDPOINT
#define _USE_Q1_14_FIXEDPOINT
#define USE_BIT_REVERSE_N1024
#define USE_TWIDDLE_TABLE_N1024

#endif
